# Generated by Django 5.2.4 on 2025-07-10 10:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=128, null=True)),
                ('camera_type', models.CharField(max_length=32, null=True)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'verbose_name': '摄像头信息',
                'verbose_name_plural': '摄像头信息',
                'db_table': 'cameras',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField()),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('state', models.IntegerField(default=1)),
                ('face_image_path', models.CharField(max_length=255)),
                ('face_embedding', models.JSONField(null=True)),
            ],
            options={
                'verbose_name': '主体',
                'verbose_name_plural': '主体',
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role_id', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='api.role')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('face_match', '识别危险人员'), ('person_fall', '人员跌倒'), ('fire', '火灾'), ('intrusion', '区域入侵'), ('conflict', '打架冲突')], max_length=32)),
                ('time', models.DateTimeField()),
                ('confidence', models.FloatField()),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('video_clip_path', models.CharField(blank=True, max_length=255, null=True)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.camera')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subject')),
            ],
            options={
                'db_table': 'event_logs',
            },
        ),
        migrations.CreateModel(
            name='AlarmLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('result', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '未处理'), (1, '处理中'), (2, '已处理')], default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(db_column='event_id', default='', on_delete=django.db.models.deletion.CASCADE, to='api.eventlog')),
            ],
            options={
                'verbose_name': '报警记录',
                'verbose_name_plural': '报警记录',
                'db_table': 'alarm_logs',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=45)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operation_log',
            },
        ),
        migrations.CreateModel(
            name='VideoAnalysisTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_video', models.FileField(upload_to='uploaded_videos/')),
                ('processed_video', models.FileField(blank=True, null=True, upload_to='processed_videos/')),
                ('status', models.SmallIntegerField(choices=[(0, '等待处理'), (1, '正在处理'), (2, '处理成功'), (-1, '处理失败')], default=0)),
                ('analysis_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '视频分析任务',
                'verbose_name_plural': '视频分析任务',
                'db_table': 'video_analysis_tasks',
            },
        ),
        migrations.CreateModel(
            name='WarningZone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, null=True)),
                ('zone_type', models.PositiveSmallIntegerField()),
                ('zone_points', models.JSONField()),
                ('is_active', models.BooleanField()),
                ('camera', models.ForeignKey(db_column='camera_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.camera')),
            ],
            options={
                'verbose_name': '预警区域',
                'verbose_name_plural': '预警区域',
                'db_table': 'warning_zones',
            },
        ),
    ]
