# Generated by Django 5.2.4 on 2025-07-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'AI 日报',
                'db_table': 'daily_report',
            },
        ),
    ]
