# Generated by Django 5.2.4 on 2025-07-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
