# Generated by Django 5.2.4 on 2025-07-09 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionlog',
            name='camera_id',
        ),
        migrations.RemoveField(
            model_name='incidentdetectionlog',
            name='camera_id',
        ),
        migrations.RemoveField(
            model_name='incidentdetectionlog',
            name='incident_type_id',
        ),
        migrations.RemoveField(
            model_name='operationlog',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='recognitionlog',
            name='camera_id',
        ),
        migrations.RemoveField(
            model_name='recognitionlog',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='warningzone',
            name='camera_id',
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='camera',
            field=models.ForeignKey(blank=True, db_column='camera_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.camera'),
        ),
        migrations.AddField(
            model_name='incidentdetectionlog',
            name='camera',
            field=models.ForeignKey(blank=True, db_column='camera_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.camera'),
        ),
        migrations.AddField(
            model_name='incidentdetectionlog',
            name='incident_type',
            field=models.ForeignKey(blank=True, db_column='incident_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.incidenttype'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recognitionlog',
            name='camera',
            field=models.ForeignKey(blank=True, db_column='camera_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.camera'),
        ),
        migrations.AddField(
            model_name='recognitionlog',
            name='person',
            field=models.ForeignKey(blank=True, db_column='person_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.subject'),
        ),
        migrations.AddField(
            model_name='warningzone',
            name='camera',
            field=models.ForeignKey(blank=True, db_column='camera_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.camera'),
        ),
    ]
