# Generated by Django 5.2.4 on 2025-07-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='password',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='url',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
