# Generated by Django 5.2.4 on 2025-07-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitionlog',
            name='video_clip',
            field=models.FileField(default='', upload_to='recognition_videos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recognitionlog',
            name='camera_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recognitionlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recognitionlog',
            name='image_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recognitionlog',
            name='person_id',
            field=models.IntegerField(),
        ),
    ]
