# Generated by Django 5.2.4 on 2025-07-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recognitionlog_video_clip_and_more'),
        ('api', '0003_remove_detectionlog_camera_id_and_more'),
    ]

    operations = [
    ]
