# Generated by Django 5.2.4 on 2025-07-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20250709_1703'),
        ('api', '0004_merge_20250709_1724'),
    ]

    operations = [
    ]
