# Generated by Django 5.2.4 on 2025-07-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_camera_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='warningzone',
            name='safe_distance',
            field=models.FloatField(blank=True, help_text='安全距离（米）', null=True),
        ),
        migrations.AddField(
            model_name='warningzone',
            name='safe_time',
            field=models.PositiveIntegerField(blank=True, help_text='安全时间（秒）', null=True),
        ),
    ]
