# Generated by Django 5.2.4 on 2025-07-09 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20250709_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField()),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'role',
            },
        ),
        migrations.RemoveField(
            model_name='recognitionlog',
            name='camera_id',
        ),
        migrations.RemoveField(
            model_name='recognitionlog',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='recognitionlog',
            name='video_clip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role_id',
        ),
        migrations.AlterField(
            model_name='recognitionlog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recognitionlog',
            name='image_path',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='VideoAnalysisTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_video', models.FileField(upload_to='uploaded_videos/')),
                ('status', models.SmallIntegerField(choices=[(0, '等待处理'), (1, '正在处理'), (2, '处理成功'), (-1, '处理失败')], default=0)),
                ('analysis_result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '视频分析任务',
                'verbose_name_plural': '视频分析任务',
                'db_table': 'video_analysis_tasks',
            },
        ),
    ]
