# Generated by Django 5.2.4 on 2025-07-17 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_warningzone_safe_distance_warningzone_safe_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='active_detectors',
            field=models.JSONField(blank=True, default=list, help_text='例如：["fall_detection", "intrusion_detection"]'),
        ),
        migrations.AlterField(
            model_name='alarmlog',
            name='event',
            field=models.OneToOneField(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='api.eventlog'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(choices=[('face_match', '识别危险人员'), ('person_fall', '人员跌倒'), ('fire', '火灾'), ('intrusion', '区域入侵'), ('conflict', '打架冲突'), ('audio_screaming', '尖叫声'), ('audio_explosion', '爆炸声'), ('audio_gunshot_gunfire', '枪声')], max_length=32),
        ),
    ]
