# Generated by Django 5.2.4 on 2025-07-10 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_role_remove_recognitionlog_camera_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysistask',
            name='processed_video',
            field=models.FileField(blank=True, null=True, upload_to='processed_videos/'),
        ),
    ]
